# Generated by Django 4.2.5 on 2023-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
