# Generated by Django 4.2.5 on 2023-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.IntegerField(blank=True, max_length=10, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
