# Generated by Django 4.2.5 on 2023-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='contact',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
